FROM registry.access.redhat.com/ubi8-dev-preview/ubi

LABEL AUTHOR="William Caban"
LABEL APP="podtools"
LABEL DESCRIPTION="Build with UBI8 Dev Preview"

WORKDIR /podtools
ADD utils ./utils/

RUN  yum    -y --nodocs install python2 iputils iproute bind-utils tar && yum clean all

# Forcing to run as non-root user
USER 1000

CMD [ "/bin/sh" ]

#
# END OF FILE
#
